services:
  redis-docker:
    container_name: redis-docker
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./app/redis/data:/data

  nginx-docker:
    container_name: nginx-docker
    image: nginx
    ports:
      - 80:80

  portainer-docker:
    image: portainer/portainer-ce:alpine
    container_name: portainer-docker
    ports:
      - 8888:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/portainer/data:/data
