services:
  # 시계열 데이터베이스
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    user: 1000:1000
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./app/prometheus:/prometheus

  # 모니터링 툴
  grafana:
    container_name: grafana
    image: grafana/grafana
    user: 1000:1000
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - ./app/grafana:/var/lib/grafana

  # 모니터링 툴
  loki:
    container_name: grafana
    image: grafana/loki
    ports:
      - 3100:3100
    depends_on:
      - grafana
    volumes:
      - ./config/loki.yml:/etc/loki/local-config.yaml

  # AI 모델 서버
  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ./app/ollama:/root/.ollama

  # AI 모델 WEB UI
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui
    ports:
      - 8282:8080
    depends_on:
      - ollama
    volumes:
      - ./app/open-webui:/app/backend/data
    extra_hosts:
      - host.docker.internal:host-gateway
