services:
  # nginx-docker:
  #   container_name: nginx-docker
  #   image: nginx
  #   ports:
  #     - 80:80

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase-docker
    restart: unless-stopped
    # command:
    #   - --encryptionEnv #optional
    #   - ENCRYPTION #optional
    # environment:
    #   ENCRYPTION: example #optional
    ports:
      - "8080:8090"
    volumes:
      - /path/to/data:/pb_data
      - /path/to/public:/pb_public #optional
      - /path/to/hooks:/pb_hooks #optional
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  redis-docker:
    container_name: redis-docker
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./app/redis/data:/data

  portainer-docker:
    image: portainer/portainer-ce:alpine
    container_name: portainer-docker
    ports:
      - 8888:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/portainer/data:/data
