global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "go-server"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      # - targets: ["172.22.160.1:8000"] # 집 PC
      # - targets: ["172.22.160.1:8000"] # 회사 PC
      - targets: ["146.56.174.134"] # Go 서버
